#!/usr/bin/env bash
n=0;
while [ $n -lt 10 ]
do
        if [ $n -eq 8 ]
        then
                echo "Hi"
                (( ++n ))
        else
                echo "Best School"
                (( ++n ))
        fi
done
